modLoader="javafml"
loaderVersion="[4,)"
license="${mod_license}"
issueTrackerURL="${issues_url}"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL="${mod_url}"
    iconFile="assets/lunaslimes/icon.png"
    authors="Lunade/AViewFromTheTop"
    description='''
Improves Slimes with new configurable features.
    '''

[[mixins]]
config="lunaslimes.mixins.json"

[[ dependencies.lunaslimes ]]
    modId="neoforge"
    type="required"
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"

[[ dependencies.lunaslimes ]]
    modId="minecraft"
    type="required"
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"

[[ dependencies.lunaslimes ]]
    modId="frozenlib"
    type="required"
    versionRange="[${frozenlib_version},)"
    ordering="NONE"
    side="BOTH"

[[ dependencies.lunaslimes ]]
    modId="cloth-config"
    type="optional"
    versionRange="*"
    ordering="NONE"
    side="BOTH"
